[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

# Build configuration for Solana BPF target
[build]
rustflags = ["--cfg", "getrandom_custom"]

[programs.devnet]
irma = "DhMQR2rJgXMR742Y7yBTm2yi8cWi3ZH8KfFEFG6SnKbA"

[programs.localnet]
irma = "FReBisHtV3Lh1eXSxmg52vuBXetUypD36YYMft7WBvvC"

[programs.mainnet]
irma = "FReBisHtV3Lh1eXSxmg52vuBXetUypD36YYMft7WBvvC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/phantom1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/read_protocol_state.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
