[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"

[build]
build_sbf = true
skip_lint = false

[features]
resolution = true
skip-lint = false

[programs.localnet]
irma = "4rVQnE69m14Qows2iwcgokb59nx7G49VD6fQ9GH9Y6KJ"
# "8zs1JbqxqLcCXzBrkMCXyY2wgSW8uk8nxYuMFEfUMQa6"

[programs.devnet]
irma = "4rVQnE69m14Qows2iwcgokb59nx7G49VD6fQ9GH9Y6KJ"

[programs.mainnet]
irma = "4rVQnE69m14Qows2iwcgokb59nx7G49VD6fQ9GH9Y6KJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/phantom1.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
