[package]
name = "irma"
version = "0.1.0"
description = "Inflation Resistant Medium of Account (IRMA)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "irma"

[features]
# default = ["idl-build"]
cpi = ["no-entrypoint"]
no-entrypoint = []
# no-idl = []
no-log-ix-name = []
# idl-build = ["anchor-lang/idl-build"]
# anchor-debug = []
# custom-heap = []
# custom-panic = []

[dependencies]
anchor-lang = "0.27.0"
openbook-v2 = { workspace = true, features = ["cpi"] }
solana-program = { workspace = true }
fixed = { workspace = true, features = ["debug-assert-in-release"] }
static_assertions = "1.1.0"
anchor-lang-idl-spec = "0.1.0"
