[package]
name = "irma"
version = "0.1.0"
description = "Inflation Resistant Medium of Account (IRMA)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "irma"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
# no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
# anchor-debug = []
# custom-heap = []
# custom-panic = []

[dependencies]
anchor-lang = "0.32.1"
openbook-v2 = { workspace = true, features = ["cpi"] }
fixed = { workspace = true }
static_assertions = "1.1.0"
